package abstractfactory;

import abstractfactory.docx.DocxExportFactory;
import abstractfactory.html.HtmlExportFactory;
import abstractfactory.pdf.PdfExportFactory;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Supplier;

/**
 * Composition root of Part B. The export family is chosen in exactly one
 * place: the FAMILIES registry below. Everything else works with the
 * ExportFactory interface.
 *
 * Usage: java abstractfactory.Main [pdf|docx|html]   (no argument = all three)
 */
public class Main {

    /** THE one place where concrete factories are named. */
    private static final Map<String, Supplier<ExportFactory>> FAMILIES = new LinkedHashMap<>();

    static {
        FAMILIES.put("pdf", PdfExportFactory::new);
        FAMILIES.put("docx", DocxExportFactory::new);
        FAMILIES.put("html", HtmlExportFactory::new);
    }

    public static void main(String[] args) {
        if (args.length == 0) {
            FAMILIES.keySet().forEach(Main::exportAs);
            return;
        }
        String format = args[0].toLowerCase();
        if (!FAMILIES.containsKey(format)) {
            System.err.println("Unknown format '" + format + "'. Choose one of: " + FAMILIES.keySet());
            System.exit(1);
        }
        exportAs(format);
    }

    private static void exportAs(String format) {
        ExportStudio studio = new ExportStudio(FAMILIES.get(format).get());
        String document = studio.export(
                "Quarterly Sales",
                List.of("Product", "Units", "Revenue"),
                List.of(List.of("Espresso Machine", "120", "60000"),
                        List.of("Grinder", "222", "60000")),
                "Generated by Report Export Studio");
        System.out.println("--- " + format.toUpperCase() + " ---");
        System.out.println(document);
        System.out.println();
    }
}
